stages:
  - setup
  - restore
  - build
  - deploy

variables:
  CI_BASEVER: 0.0.0

setup:
  stage: setup
  tags:
    - linux
    - docker
  image: docker pull mcr.microsoft.com/dotnet/sdk:latest
  script:
    - |
      NOW=$(date +"%Y%m%d")
      echo "CI_ASMVER=$CI_BASEVER.$NOW" >> build.env
      if [ "$CI_COMMIT_TAG" -ne ""]; then
        echo "CI_SEMVER=$CI_BASEVER" >> build.env
      else
        BRANCHNAME=$(echo "$CI_COMMIT_BRANCH" | sed "s/\//-/g")
        echo "CI_SEMVER=$CI_BASEVER-$BRANCHNAME-$CI_BUILD_ID" >> build.env
      fi
  artifacts:
    reports:
      dotenv: build.env
    expire_in: 1 week

restore:
  stage: restore
  tags:
    - linux
    - docker
  image: docker pull mcr.microsoft.com/dotnet/sdk:latest
  before_script:
    - dotnet nuget remove source gitlab
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
  script:
    - dotnet restore Faelyn.sln -c Release /p:Version=$env:CI_ASMVER /p:InformationalVersion=$env:CI_SEMVER /p:PackageVersion=$env:CI_SEMVER
  after_script:
    - dotnet nuget remove source gitlab
  artifacts:
    paths:
      - Build/libs
    expire_in: 1 week
  needs:
    - job: setup
      artifacts: true

build:
  stage: build
  tags:
    - windows
    - dotnet
    - powershell
  script:
    - dotnet build Faelyn.sln --no-restore -c Release /p:Version=$env:CI_ASMVER /p:InformationalVersion=$env:CI_SEMVER /p:PackageVersion=$env:CI_SEMVER
  artifacts:
    paths:
      - Build/tmp/packages
    expire_in: 1 week
  needs:
    - job: setup
      artifacts: true
    - job: restore
      artifacts: true
    
deploy:
  stage: deploy
  tags:
    - linux
    - docker
  image: docker pull mcr.microsoft.com/dotnet/sdk:latest
  before_script:
    - dotnet nuget remove source gitlab
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
  script:
    - dotnet nuget push "Build/tmp/packages/*.nupkg" --source gitlab
    - dotnet nuget push "Build/tmp/packages/*.snupkg" --source gitlab
  after_script:
    - dotnet nuget remove source gitlab
  needs:
    - job: setup
      artifacts: true
    - job: build
      artifacts: true