stages:
  - versioning
  - build

versioning:
  stage: versioning
  tags:
    - windows
    - powershell
  script:
    - $vs = ([xml] [IO.File]::ReadAllText("Build/version.config")).version
    - echo "SEMVER=$($vs.major).$($vs.minor).$CI_BUILD_ID" >> Build/build.env
  artifacts:
    reports:
      dotenv: Build/build.env

build:
  stage: build
  tags:
   - windows
   - dotnet
   - powershell
  script:
    - dotnet build Faelyn.sln --configuration Release /p:Version=$SEMVER /p:PackageVersion=$SEMVER
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "Build/tmp/out/*.nupkg" --source gitlab
    - dotnet nuget push "Build/tmp/out/*.snupkg" --source gitlab
  needs:
    - job: versioning
      artifacts: true
