stages:
  - build

build:
  stage: build
  tags:
  - windows
  - powershell
  script:
    - dotnet restore Faelyn.sln
    - dotnet build --no-restore Faelyn.sln
  artifacts:
    paths:
      - ./Build/tmp/packages
    expire_in: 1 month