stages:
  - build

variables:
  VERSION: "$CI_COMMIT_TAG.$CI_JOB_ID"
  PACKAGEVERSION: "$CI_COMMIT_TAG"

build:
  stage: build
  tags:
  - windows
  - powershell
  script:
    - dotnet build Faelyn.sln --configuration Release /p:Version=$VERSION /p:PackageVersion=$PACKAGEVERSION
  artifacts:
    paths:
      - ./Build/tmp/packages
    expire_in: 1 month