stages:
  - build

build:
  stage: build
  tags:
   - windows
   - dotnet
   - powershell
  before_script:
    - export "CI_JOB_SECOFDAY=$([System.Convert]::ToInt32((Get-Date).TimeOfDay.TotalSeconds))"
    - export "CI_JOB_SEMVER=$(Get-Date yy.mm.dd)"
    - export "CI_JOB_VERSION=$CI_JOB_SEMVER.$CI_JOB_SECOFDAY"
    - echo $CI_JOB_VERSION
  script:
    - dotnet build Faelyn.sln --configuration Release /p:Version=$VERSION /p:PackageVersion=$PACKAGEVERSION
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "Build/tmp/out/*.nupkg" --source gitlab
    - dotnet nuget push "Build/tmp/out/*.snupkg" --source gitlab